package:
  name: conda-forge-build-setup
  version: 3.2.1

build:
  number: 0
  script:
    - if not exist "%LIBRARY_BIN%" mkdir "%LIBRARY_BIN%"                                                                 # [win]
    - mkdir -p "${PREFIX}/bin"                                                                                           # [unix]
    - COPY "%RECIPE_DIR%\\run_conda_forge_build_setup_win" "%SCRIPTS%\\run_conda_forge_build_setup.bat"                  # [win]
    - cp "${RECIPE_DIR}/run_conda_forge_build_setup_osx" "${PREFIX}/bin/run_conda_forge_build_setup"                     # [osx]
    - cp "${RECIPE_DIR}/run_conda_forge_build_setup_linux" "${PREFIX}/bin/run_conda_forge_build_setup"                   # [linux]
    - COPY "%RECIPE_DIR%\\upload_or_check_non_existence.py" "%SCRIPTS%\\upload_or_check_non_existence.py"                # [win]
    - cp "${RECIPE_DIR}/upload_or_check_non_existence.py" "${PREFIX}/bin/upload_or_check_non_existence.py"               # [osx]

test:
  commands:
    - if not exist "%SCRIPTS%\\run_conda_forge_build_setup.bat" exit 1                                                   # [win]
    - test -f "${PREFIX}/bin/run_conda_forge_build_setup"                                                                # [unix]

about:
  home: https://github.com/conda-forge/conda-forge-build-setup-feedstock
  summary: A package installed by conda-forge each time a build is run on CI. This package has side-effects to your conda config.
  license: BSD 3-clause

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - pelson
